name: simple_local_auth
description: A Flutter plugin for local biometric authentication with clean API and detailed error handling.
version: 0.1.0
homepage: https://github.com/tamremariam/simple_local_auth
repository: https://github.com/tamremariam/simple_local_auth.git
issue_tracker: https://github.com/tamremariam/simple_local_auth/issues


environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  mockito: ^5.4.6

flutter:
  plugin:
    platforms:
      android:
        package: com.example.simple_local_auth
        pluginClass: SimpleLocalAuthPlugin
      ios:
        pluginClass: SimpleLocalAuthPlugin

